os:
  - linux
  - osx

osx_image: beta-xcode6.2

language: cpp

compiler:
 - gcc
 - clang

sudo: true

addons:
  apt:
    packages:
     - cmake

script:
 - Testing/travisCITest.sh
 - /usr/local/Trolltech/Qt-4.8.7/bin/qmake --version |grep 'Using Qt version 4.8.7' || die "Could not run Qt 4.8.7"

