os:
  - linux
  - osx

# See https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
osx_image: xcode7.3 # 10.11

language: cpp

compiler:
 - gcc
 - clang

sudo: true

addons:
  apt:
    packages:
     - cmake

script:
 - ./Testing/travisCITest.sh

